### ISSUE TITLE
[Linux] Sven Co-op games.h support

### ISSUE THREAD

**Issue by APGRoboCop** [SamVanheer/Metamod-P-CMake#4]
I've been trying to get Metamod-P-39 to work on my Sven server, but I had to rename server.so file from /dlls folder to hl_i386.so in order for it to work. If I am not mistaken it appears the games.h Header file may need a fix at line 113. Why not try and recompile that Metamod src code but with this line replaced:-

`	{"svencoop",          "server.so",       		    "server.dll",        "Sven Coop"},`

**Comment by SamVanheer** [comment]
This is the normal Metamod-P for vanilla Half-Life. You want the Sven Co-op 5.0 fork: https://github.com/swmpdg/Metamod-P-CMake-svencoop
That one has Sven Co-op support built in: https://github.com/swmpdg/Metamod-P-CMake-svencoop/blob/f903c7cf910ee132f5c1d9806cacd079227bb924/metamod/games.h#L114

I made that one as well, but i took the repository offline to avoid people asking me to support Sven Co-op. If you want support for it i can put it back, but i'd prefer not to have to perform maintenance for Sven Co-op all the time.
